server:
  port: 6789
  servlet:
    context-path: /reviewapp


myapp:
  value: "Doing Work"
spring:
  datasource:
    username: postgres
    password: deviantwriter14
    url: jdbc:postgresql://java-enterprise-22075.cgvdqjwau9al.us-west-1.rds.amazonaws.com:5432/my_database
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE